-- MySQL Script generated by MySQL Workbench
-- 02/10/15 14:24:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema etur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema etur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `etur` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `etur` ;

-- -----------------------------------------------------
-- Table `etur`.`idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`idiomas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_titulo` LONGTEXT NULL,
  `idioma_img_path` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`categorias_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`categorias_articulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `categoria_articulo_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `categoria_articulo_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`articulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `categoria_articulo_id` INT NULL,
  `articulo_nombre` LONGTEXT NULL,
  `articulo_titulo` LONGTEXT NULL,
  `articulo_descripcion` LONGTEXT NULL,
  `articulo_tags` LONGTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_id_idx` (`categoria_articulo_id` ASC),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `categoria_articulo_id`
    FOREIGN KEY (`categoria_articulo_id`)
    REFERENCES `etur`.`categorias_articulo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`imagenes_articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`imagenes_articulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `articulo_id` INT NULL,
  `img_path` LONGTEXT NULL,
  `img_size` LONGTEXT NULL,
  `img_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `articulo_id_idx` (`articulo_id` ASC),
  CONSTRAINT `articulo_id`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `etur`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`categorias_etur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`categorias_etur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `categorias_etur_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `categoria_etur_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`subcategorias_etur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`subcategorias_etur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `subcategoria_etur_titulo` LONGTEXT NULL,
  `categoria_etur_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_etur_id_idx` (`categoria_etur_id` ASC),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `categoria_etur_id`
    FOREIGN KEY (`categoria_etur_id`)
    REFERENCES `etur`.`categorias_etur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subcategoria_etur_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`atractivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`atractivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `subcategoria_etur_id` INT NULL,
  `atractivo_titulo` VARCHAR(45) NULL,
  `atractivo_direccion` LONGTEXT NULL,
  `atractivo_resumen` LONGTEXT NULL,
  `atractivo_descripcion` LONGTEXT NULL,
  `atractivo_telefono` LONGTEXT NULL,
  `atractivo_website` LONGTEXT NULL,
  `atractivo_horarios` LONGTEXT NULL,
  `atractivo_galerias` LONGTEXT NULL,
  `atractivo_lat_long` LONGTEXT NULL,
  `atractivo_tags` LONGTEXT NULL,
  `atractivo_publicar` INT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcategoria_etur_id_idx` (`subcategoria_etur_id` ASC),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `subcategoria_etur_id`
    FOREIGN KEY (`subcategoria_etur_id`)
    REFERENCES `etur`.`subcategorias_etur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `atractivo_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`articulos_atractivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`articulos_atractivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `articulo_id` INT NULL,
  `atractivo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `articulo_id_idx` (`articulo_id` ASC),
  INDEX `atractivo_id_idx` (`atractivo_id` ASC),
  CONSTRAINT `articulo_atractivo_articulo_id`
    FOREIGN KEY (`articulo_id`)
    REFERENCES `etur`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `articulo_atractivo_atractivo_id`
    FOREIGN KEY (`atractivo_id`)
    REFERENCES `etur`.`atractivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`imagenes_atractivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`imagenes_atractivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `atractivo_id` INT NULL,
  `img_path` LONGTEXT NULL,
  `img_size` LONGTEXT NULL,
  `img_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `atractivo_id_idx` (`atractivo_id` ASC),
  CONSTRAINT `atractivo_id`
    FOREIGN KEY (`atractivo_id`)
    REFERENCES `etur`.`atractivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`agendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`agendas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `atractivo_id` INT NULL,
  `agenda_titulo` LONGTEXT NULL,
  `agenda_descripcion` LONGTEXT NULL,
  `agenda_fecha` LONGTEXT NULL,
  `agenda_lugar` LONGTEXT NULL,
  `agenda_lat_long` LONGTEXT NULL,
  `agenda_horario` LONGTEXT NULL,
  `agenda_tags` LONGTEXT NULL,
  `agenda_organiza` LONGTEXT NULL,
  `agenda_mas_info` LONGTEXT NULL,
  `agenda_anual` INT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  INDEX `atractivo_id_idx` (`atractivo_id` ASC),
  CONSTRAINT `agenda_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `agenda_atractivo_id`
    FOREIGN KEY (`atractivo_id`)
    REFERENCES `etur`.`atractivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`imagenes_agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`imagenes_agenda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agenda_id` INT NULL,
  `img_path` LONGTEXT NULL,
  `img_size` LONGTEXT NULL,
  `img_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `agenda_id_idx` (`agenda_id` ASC),
  CONSTRAINT `agenda_id`
    FOREIGN KEY (`agenda_id`)
    REFERENCES `etur`.`agendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`circuitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`circuitos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `circuito_titulo` LONGTEXT NULL,
  `circuito_descripcion` LONGTEXT NULL,
  `circuito_tipo` LONGTEXT NULL,
  `circuito_recorrido` LONGTEXT NULL,
  `circuito_tags` LONGTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `circuito_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`atractivos_circuitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`atractivos_circuitos` (
  `id` INT NOT NULL,
  `atractivo_id` INT NULL,
  `circuito_id` INT NULL,
  `atractivos_circuitos_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `circuito_id_idx` (`circuito_id` ASC),
  INDEX `atractivo_id_idx` (`atractivo_id` ASC),
  CONSTRAINT `atractivo_circuito_circuito_id`
    FOREIGN KEY (`circuito_id`)
    REFERENCES `etur`.`circuitos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `atractivo_circuito_atractivo_id`
    FOREIGN KEY (`atractivo_id`)
    REFERENCES `etur`.`atractivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`tipos_establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`tipos_establecimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `tipo_establecimiento_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `tipo_establecimiento_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`categorias_establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`categorias_establecimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `tipo_establecimiento_id` INT NULL,
  `categoria_establecimiento_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  INDEX `tipo_establecimiento_id_idx` (`tipo_establecimiento_id` ASC),
  CONSTRAINT `categoria_establecimiento_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipo_establecimiento_id`
    FOREIGN KEY (`tipo_establecimiento_id`)
    REFERENCES `etur`.`tipos_establecimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`ubicaciones_establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`ubicaciones_establecimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ubicacion_establecimiento_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`caracteristicas_establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`caracteristicas_establecimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `caracteristica_establecimiento_titulo` LONGTEXT NULL,
  `caracteristicas_establecimiento_img_path` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `caracteristica_establecimiento_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`establecimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`establecimientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `tipo_establecimiento_id` INT NULL,
  `categoria_establecimiento_id` INT NULL,
  `caracteristica_establecimiento_id` INT NULL,
  `ubicacion_establecimiento_id` INT NULL,
  `establecimiento_titulo` LONGTEXT NULL,
  `establecimiento_descripcion` LONGTEXT NULL,
  `establecimiento_direccion` LONGTEXT NULL,
  `establecimiento_lat_long` LONGTEXT NULL,
  `establecimiento_website` LONGTEXT NULL,
  `establecimiento_email` LONGTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  INDEX `categoria_establecimiento_id_idx` (`categoria_establecimiento_id` ASC),
  INDEX `tipo_establecimiento_id_idx` (`tipo_establecimiento_id` ASC),
  INDEX `ubicacion_establecimiento_id_idx` (`ubicacion_establecimiento_id` ASC),
  INDEX `caracterisitca_establecimiento_id_idx` (`caracteristica_establecimiento_id` ASC),
  CONSTRAINT `establecimiento_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categoria_establecimiento_id`
    FOREIGN KEY (`categoria_establecimiento_id`)
    REFERENCES `etur`.`categorias_establecimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `establecimiento_tipo_establecimiento_id`
    FOREIGN KEY (`tipo_establecimiento_id`)
    REFERENCES `etur`.`tipos_establecimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ubicacion_establecimiento_id`
    FOREIGN KEY (`ubicacion_establecimiento_id`)
    REFERENCES `etur`.`ubicaciones_establecimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `caracterisitca_establecimiento_id`
    FOREIGN KEY (`caracteristica_establecimiento_id`)
    REFERENCES `etur`.`caracteristicas_establecimiento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `producto_titulo` LONGTEXT NULL,
  `producto_descripcion` LONGTEXT NULL,
  `producto_precio` LONGTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `producto_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`imagenes_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`imagenes_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NULL,
  `img_path` LONGTEXT NULL,
  `img_size` LONGTEXT NULL,
  `img_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `producto_id_idx` (`producto_id` ASC),
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `etur`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`suscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`suscripciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `suscripcion_email` LONGTEXT NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`posiciones_banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`posiciones_banner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posiciones_banner_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `banner_titulo` LONGTEXT NULL,
  `posicion_banner_id` INT NULL,
  `banner_path` LONGTEXT NULL,
  `banner_size` LONGTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `posicion_banner_id_idx` (`posicion_banner_id` ASC),
  CONSTRAINT `posicion_banner_id`
    FOREIGN KEY (`posicion_banner_id`)
    REFERENCES `etur`.`posiciones_banner` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`permisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permiso_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`grupos_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`grupos_permisos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NULL,
  `permiso_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `grupo_id_idx` (`grupo_id` ASC),
  INDEX `permiso_id_idx` (`permiso_id` ASC),
  CONSTRAINT `grupo_permiso_grupo_id`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `etur`.`grupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `grupo_permiso_permiso_id`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `etur`.`permisos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NULL,
  `usuario_nombre` LONGTEXT NULL,
  `usuario_apellido` LONGTEXT NULL,
  `usuario_telefono` LONGTEXT NULL,
  `usuario_direccion` LONGTEXT NULL,
  `usuario_dni` LONGTEXT NULL,
  `usuario_email` LONGTEXT NULL,
  `usuario_username` LONGTEXT NULL,
  `usuario_password` LONGTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `grupo_id_idx` (`grupo_id` ASC),
  CONSTRAINT `grupo_id`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `etur`.`grupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`multimedias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`multimedias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `multimedia_titulo` LONGTEXT NULL,
  `multimedia_resumen` LONGTEXT NULL,
  `multimedia_video` LONGTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `multimedia_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`imagenes_multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`imagenes_multimedia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `multimedia_id` INT NULL,
  `img_path` LONGTEXT NULL,
  `img_size` LONGTEXT NULL,
  `img_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `multimedia_id_idx` (`multimedia_id` ASC),
  CONSTRAINT `multimedia_id`
    FOREIGN KEY (`multimedia_id`)
    REFERENCES `etur`.`multimedias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`categorias_informacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`categorias_informacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `categorias_informacion_titulo` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `categoria_informacion_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`subcategorias_informacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`subcategorias_informacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idioma_id` INT NULL,
  `subcategorias_informacion_titulo` LONGTEXT NULL,
  `categoria_informacion_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_informacion_id_idx` (`categoria_informacion_id` ASC),
  INDEX `idioma_id_idx` (`idioma_id` ASC),
  CONSTRAINT `categoria_informacion_id`
    FOREIGN KEY (`categoria_informacion_id`)
    REFERENCES `etur`.`categorias_informacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subcategoria_informacion_idioma_id`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `etur`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `etur`.`informaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etur`.`informaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subcategoria_informacion_id` INT NULL,
  `informacion_titulo` LONGTEXT NULL,
  `informacion_email` LONGTEXT NULL,
  `informacion_website` LONGTEXT NULL,
  `informacion_lat_long` LONGTEXT NULL,
  `informacion_direccion` LONGTEXT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `user` LONGTEXT NULL,
  `state` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcategoria_informacion_id_idx` (`subcategoria_informacion_id` ASC),
  CONSTRAINT `subcategoria_informacion_id`
    FOREIGN KEY (`subcategoria_informacion_id`)
    REFERENCES `etur`.`subcategorias_informacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
